### ISSUE TITLE
ProcessRunSupportTests uses MainActor.assertIsolated (Swift 5.9+) on Swift 5.7 runner (run 31985)

### ISSUE THREAD

**Issue by Gronod** [Gronod/iccery-v2-mac#116]
_Migrated from Gitea [https://git.i3omb.com/gronod/iccery-v2-mac/issues/115](https://git.i3omb.com/gronod/iccery-v2-mac/issues/115). Original author `gronod` · opened `2026-09-12T08:06:37Z`._

Run 31985 (job 33232) failed at `Build for testing (universal)` on the macos-12 runner (Xcode 14.2 / Swift 5.7) — the app target now compiles; the ICCeryCoreTests bundle does not:

```
Tests/ICCeryCoreTests/ProcessRunSupportTests.swift:24:27: error: type 'MainActor' has no member 'assertIsolated'
```

`MainActor.assertIsolated()` was added in Swift 5.9 (Xcode 15). The test only needs to prove the coalesced log sink runs on the main actor; `XCTAssertTrue(Thread.isMainThread)` expresses that and works on Swift 5.7.
